#ifndef GENERATED_ASN1SCC_drivers_config_H
#define GENERATED_ASN1SCC_drivers_config_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "linux-serial-ccsds-driver.h"
#include "samv71-rtems-serial-driver.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const Serial_CCSDS_Linux_Conf_T pohidrv_node_1_uart0;
extern const Serial_SamV71_Rtems_Conf_T pohidrv_node_2_uart0;

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

#ifdef __cplusplus
}

#endif

#endif
