/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>

#include "linux-serial-ccsds-driver.h"
#include "samv71-rtems-serial-driver.h"

#include "drivers_config.h"

const Serial_CCSDS_Linux_Conf_T pohidrv_node_1_uart0 = {
	.devname = "/home/taste/SAMV71",
	.speed = Serial_CCSDS_Linux_Baudrate_T_b9600,
	.parity = Serial_CCSDS_Linux_Parity_T_even,
	.bits = 8UL,
	.use_paritybit = FALSE,
	.exist = { .speed = 1, .parity = 1, .bits = 1, .use_paritybit = 1 }
};
const Serial_SamV71_Rtems_Conf_T pohidrv_node_2_uart0 = {
	.devname = uart4,
	.speed = Serial_SamV71_Rtems_Baudrate_T_b9600,
	.parity = Serial_SamV71_Rtems_Parity_T_even
};
