/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>

#include "samv71-rtems-serial-driver.h"
#include "samv71-rtems-can-driver.h"

#include "drivers_config.h"

const Serial_SamV71_Rtems_Conf_T pohidrv_node_1_uart4 = {
	.devname = { .kind = uart0_PRESENT,
		     .u = { .uart0 = { .tx = pa10, .rx = pa9 } } },
	.speed = b38400,
	.parity = none,
	.transmit_mode = escaped_packets,
	.exist = { .transmit_mode = 1 }
};
const CAN_Samv71_Rtems_Conf_T pohidrv_node_1_can0 = {
	.can_interface = mcan_interface_mcan0,
	.bit_rate_prescaler = 0UL,
	.synchronization_jump = 2UL,
	.time_segments_after_sample_point = 2UL,
	.time_segments_before_sample_point = 15UL,
	.pck_source = pck_clock_source_plla_clock,
	.pck_prescaler = 14UL,
	.address = { .kind = static_can_id_PRESENT,
		     .u = { .static_can_id = { .kind = can_id_standard_PRESENT,
					       .u = { .can_id_standard =
							      123UL } } } },
	.exist = { .bit_rate_prescaler = 1,
		   .synchronization_jump = 1,
		   .time_segments_after_sample_point = 1,
		   .time_segments_before_sample_point = 1,
		   .pck_source = 1,
		   .pck_prescaler = 1 }
};
const Serial_SamV71_Rtems_Conf_T pohidrv_node_2_uart4 = {
	.devname = { .kind = uart0_PRESENT,
		     .u = { .uart0 = { .tx = pa10, .rx = pa9 } } },
	.speed = b38400,
	.parity = none,
	.transmit_mode = escaped_packets,
	.exist = { .transmit_mode = 1 }
};
const CAN_Samv71_Rtems_Conf_T pohidrv_node_2_can0 = {
	.can_interface = mcan_interface_mcan0,
	.bit_rate_prescaler = 0UL,
	.synchronization_jump = 2UL,
	.time_segments_after_sample_point = 2UL,
	.time_segments_before_sample_point = 15UL,
	.pck_source = pck_clock_source_plla_clock,
	.pck_prescaler = 14UL,
	.address = { .kind = static_can_id_PRESENT,
		     .u = { .static_can_id = { .kind = can_id_standard_PRESENT,
					       .u = { .can_id_standard =
							      125UL } } } },
	.exist = { .bit_rate_prescaler = 1,
		   .synchronization_jump = 1,
		   .time_segments_after_sample_point = 1,
		   .time_segments_before_sample_point = 1,
		   .pck_source = 1,
		   .pck_prescaler = 1 }
};
