/* File generated by kazoo for TASTE - do not edit */
#include "interfaces_info.h"

thread_info threads_info[RUNTIME_THREAD_COUNT];

rtems_id interface_to_queue_map[RUNTIME_THREAD_COUNT];

uint32_t maximum_queued_items[RUNTIME_THREAD_COUNT];
