#ifndef GENERATED_ASN1SCC_linux_serial_ccsds_driver_H
#define GENERATED_ASN1SCC_linux_serial_ccsds_driver_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
	Serial_CCSDS_Linux_Baudrate_T_b9600 = 0,
	Serial_CCSDS_Linux_Baudrate_T_b19200 = 1,
	Serial_CCSDS_Linux_Baudrate_T_b38400 = 2,
	Serial_CCSDS_Linux_Baudrate_T_b57600 = 3,
	Serial_CCSDS_Linux_Baudrate_T_b115200 = 4,
	Serial_CCSDS_Linux_Baudrate_T_b230400 = 5
} Serial_CCSDS_Linux_Baudrate_T;

// please use the following macros to avoid breaking code.
#define Serial_CCSDS_Linux_Baudrate_T_b9600 Serial_CCSDS_Linux_Baudrate_T_b9600
#define Serial_CCSDS_Linux_Baudrate_T_b19200 \
	Serial_CCSDS_Linux_Baudrate_T_b19200
#define Serial_CCSDS_Linux_Baudrate_T_b38400 \
	Serial_CCSDS_Linux_Baudrate_T_b38400
#define Serial_CCSDS_Linux_Baudrate_T_b57600 \
	Serial_CCSDS_Linux_Baudrate_T_b57600
#define Serial_CCSDS_Linux_Baudrate_T_b115200 \
	Serial_CCSDS_Linux_Baudrate_T_b115200
#define Serial_CCSDS_Linux_Baudrate_T_b230400 \
	Serial_CCSDS_Linux_Baudrate_T_b230400

#define ERR_SERIAL_CCSDS_LINUX_BAUDRATE_T \
	1 /*b9600 | b19200 | b38400 | b57600 | b115200 | b230400*/
flag Serial_CCSDS_Linux_Baudrate_T_IsConstraintValid(
	const Serial_CCSDS_Linux_Baudrate_T *pVal, int *pErrCode);

void Serial_CCSDS_Linux_Baudrate_T_Initialize(
	Serial_CCSDS_Linux_Baudrate_T *pVal);
typedef enum {
	Serial_CCSDS_Linux_Parity_T_even = 0,
	Serial_CCSDS_Linux_Parity_T_odd = 1
} Serial_CCSDS_Linux_Parity_T;

// please use the following macros to avoid breaking code.
#define Serial_CCSDS_Linux_Parity_T_even Serial_CCSDS_Linux_Parity_T_even
#define Serial_CCSDS_Linux_Parity_T_odd Serial_CCSDS_Linux_Parity_T_odd

#define ERR_SERIAL_CCSDS_LINUX_PARITY_T 6 /*even | odd*/
flag Serial_CCSDS_Linux_Parity_T_IsConstraintValid(
	const Serial_CCSDS_Linux_Parity_T *pVal, int *pErrCode);

void Serial_CCSDS_Linux_Parity_T_Initialize(Serial_CCSDS_Linux_Parity_T *pVal);
/*-- Serial_CCSDS_Linux_Conf_T --------------------------------------------*/
typedef char Serial_CCSDS_Linux_Conf_T_devname[25];
typedef asn1SccUint Serial_CCSDS_Linux_Conf_T_bits;

typedef struct {
	unsigned long speed : 1;
	unsigned long parity : 1;
	unsigned long bits : 1;
	unsigned long use_paritybit : 1;
} Serial_CCSDS_Linux_Conf_T_exist;
typedef struct {
	Serial_CCSDS_Linux_Conf_T_devname devname;
	Serial_CCSDS_Linux_Baudrate_T speed;
	Serial_CCSDS_Linux_Parity_T parity;
	Serial_CCSDS_Linux_Conf_T_bits bits;
	flag use_paritybit;

	Serial_CCSDS_Linux_Conf_T_exist exist;

} Serial_CCSDS_Linux_Conf_T;

#define ERR_SERIAL_CCSDS_LINUX_CONF_T_DEVNAME 11 /*(SIZE (1..24))*/
flag Serial_CCSDS_Linux_Conf_T_devname_IsConstraintValid(
	const Serial_CCSDS_Linux_Conf_T_devname pVal, int *pErrCode);

#define ERR_SERIAL_CCSDS_LINUX_CONF_T_BITS 36 /*(7 .. 8)*/
flag Serial_CCSDS_Linux_Conf_T_bits_IsConstraintValid(
	const Serial_CCSDS_Linux_Conf_T_bits *pVal, int *pErrCode);

#define ERR_SERIAL_CCSDS_LINUX_CONF_T 46 /**/
#define ERR_SERIAL_CCSDS_LINUX_CONF_T_SPEED_2 21 /**/
#define ERR_SERIAL_CCSDS_LINUX_CONF_T_PARITY_2 31 /**/
#define ERR_SERIAL_CCSDS_LINUX_CONF_T_USE_PARITYBIT 41 /**/
flag Serial_CCSDS_Linux_Conf_T_IsConstraintValid(
	const Serial_CCSDS_Linux_Conf_T *pVal, int *pErrCode);

void Serial_CCSDS_Linux_Conf_T_devname_Initialize(
	Serial_CCSDS_Linux_Conf_T_devname pVal);
void Serial_CCSDS_Linux_Conf_T_bits_Initialize(
	Serial_CCSDS_Linux_Conf_T_bits *pVal);
void Serial_CCSDS_Linux_Conf_T_Initialize(Serial_CCSDS_Linux_Conf_T *pVal);

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

#ifdef __cplusplus
}

#endif

#endif
