/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>


#include "samv71-rtems-can-driver.h"



flag CAN_Samv71_Rtems_Interface_T_IsConstraintValid(const CAN_Samv71_Rtems_Interface_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((((*(pVal)) == mcan_interface_mcan0)) || (((*(pVal)) == mcan_interface_mcan1)));
    *pErrCode = ret ? 0 :  ERR_CAN_SAMV71_RTEMS_INTERFACE_T;

	return ret;
}

void CAN_Samv71_Rtems_Interface_T_Initialize(CAN_Samv71_Rtems_Interface_T* pVal)
{
	(void)pVal;


	(*(pVal)) = mcan_interface_mcan0;
}


flag CAN_Samv71_Rtems_PCK_Clock_Source_IsConstraintValid(const CAN_Samv71_Rtems_PCK_Clock_Source* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((((*(pVal)) == pck_clock_source_main_clock)) || (((*(pVal)) == pck_clock_source_plla_clock)));
    *pErrCode = ret ? 0 :  ERR_CAN_SAMV71_RTEMS_PCK_CLOCK_SOURCE;

	return ret;
}

void CAN_Samv71_Rtems_PCK_Clock_Source_Initialize(CAN_Samv71_Rtems_PCK_Clock_Source* pVal)
{
	(void)pVal;


	(*(pVal)) = pck_clock_source_main_clock;
}


flag CAN_Samv71_Rtems_PCK_Prescaler_IsConstraintValid(const CAN_Samv71_Rtems_PCK_Prescaler* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 255UL);
    *pErrCode = ret ? 0 :  ERR_CAN_SAMV71_RTEMS_PCK_PRESCALER;

	return ret;
}

void CAN_Samv71_Rtems_PCK_Prescaler_Initialize(CAN_Samv71_Rtems_PCK_Prescaler* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}


flag CAN_Samv71_Rtems_Data_Synchronization_Jump_Width_IsConstraintValid(const CAN_Samv71_Rtems_Data_Synchronization_Jump_Width* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 7UL);
    *pErrCode = ret ? 0 :  ERR_CAN_SAMV71_RTEMS_DATA_SYNCHRONIZATION_JUMP_WIDTH;

	return ret;
}

void CAN_Samv71_Rtems_Data_Synchronization_Jump_Width_Initialize(CAN_Samv71_Rtems_Data_Synchronization_Jump_Width* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}


flag CAN_Samv71_Rtems_Data_Time_Segment_Before_Sample_Point_IsConstraintValid(const CAN_Samv71_Rtems_Data_Time_Segment_Before_Sample_Point* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((1UL <= (*(pVal))) && ((*(pVal)) <= 31UL));
    *pErrCode = ret ? 0 :  ERR_CAN_SAMV71_RTEMS_DATA_TIME_SEGMENT_BEFORE_SAMPLE_POINT;

	return ret;
}

void CAN_Samv71_Rtems_Data_Time_Segment_Before_Sample_Point_Initialize(CAN_Samv71_Rtems_Data_Time_Segment_Before_Sample_Point* pVal)
{
	(void)pVal;


	(*(pVal)) = 1UL;
}


flag CAN_Samv71_Rtems_Data_Time_Segment_After_Sample_Point_IsConstraintValid(const CAN_Samv71_Rtems_Data_Time_Segment_After_Sample_Point* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 15UL);
    *pErrCode = ret ? 0 :  ERR_CAN_SAMV71_RTEMS_DATA_TIME_SEGMENT_AFTER_SAMPLE_POINT;

	return ret;
}

void CAN_Samv71_Rtems_Data_Time_Segment_After_Sample_Point_Initialize(CAN_Samv71_Rtems_Data_Time_Segment_After_Sample_Point* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}


flag CAN_Samv71_Rtems_Data_Bit_Rate_Prescaler_IsConstraintValid(const CAN_Samv71_Rtems_Data_Bit_Rate_Prescaler* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 31UL);
    *pErrCode = ret ? 0 :  ERR_CAN_SAMV71_RTEMS_DATA_BIT_RATE_PRESCALER;

	return ret;
}

void CAN_Samv71_Rtems_Data_Bit_Rate_Prescaler_Initialize(CAN_Samv71_Rtems_Data_Bit_Rate_Prescaler* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}


flag CAN_Samv71_Rtems_Data_Structure_T_IsConstraintValid(const CAN_Samv71_Rtems_Data_Structure_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((((*(pVal)) == plain)) || (((*(pVal)) == can_id_first)));
    *pErrCode = ret ? 0 :  ERR_CAN_SAMV71_RTEMS_DATA_STRUCTURE_T;

	return ret;
}

void CAN_Samv71_Rtems_Data_Structure_T_Initialize(CAN_Samv71_Rtems_Data_Structure_T* pVal)
{
	(void)pVal;


	(*(pVal)) = plain;
}


flag CAN_Samv71_Rtems_Standard_Can_Id_IsConstraintValid(const CAN_Samv71_Rtems_Standard_Can_Id* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 2047UL);
    *pErrCode = ret ? 0 :  ERR_CAN_SAMV71_RTEMS_STANDARD_CAN_ID;

	return ret;
}

void CAN_Samv71_Rtems_Standard_Can_Id_Initialize(CAN_Samv71_Rtems_Standard_Can_Id* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}


flag CAN_Samv71_Rtems_Extended_Can_Id_IsConstraintValid(const CAN_Samv71_Rtems_Extended_Can_Id* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 536870911UL);
    *pErrCode = ret ? 0 :  ERR_CAN_SAMV71_RTEMS_EXTENDED_CAN_ID;

	return ret;
}

void CAN_Samv71_Rtems_Extended_Can_Id_Initialize(CAN_Samv71_Rtems_Extended_Can_Id* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}


flag CAN_Samv71_Rtems_Can_Id_IsConstraintValid(const CAN_Samv71_Rtems_Can_Id* pVal, int* pErrCode)
{
    flag ret = TRUE;
    switch (pVal->kind) {
        case can_id_standard_PRESENT : 
            ret = CAN_Samv71_Rtems_Standard_Can_Id_IsConstraintValid((&(pVal->u.can_id_standard)), pErrCode);
            break;          
        case can_id_extended_PRESENT : 
            ret = CAN_Samv71_Rtems_Extended_Can_Id_IsConstraintValid((&(pVal->u.can_id_extended)), pErrCode);
            break;          
        default: /*COVERAGE_IGNORE*/
    	    *pErrCode = ERR_CAN_SAMV71_RTEMS_CAN_ID;      /*COVERAGE_IGNORE*/
    	    ret = FALSE;                               /*COVERAGE_IGNORE*/
    }

	return ret;
}

void CAN_Samv71_Rtems_Can_Id_Initialize(CAN_Samv71_Rtems_Can_Id* pVal)
{
	(void)pVal;


	pVal->kind = can_id_standard_PRESENT;
	pVal->u.can_id_standard = 0UL;
}


flag CAN_Samv71_Rtems_Dummy_IsConstraintValid(const CAN_Samv71_Rtems_Dummy* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
    ret = TRUE;
    *pErrCode = 0;

	return ret;
}

void CAN_Samv71_Rtems_Dummy_Initialize(CAN_Samv71_Rtems_Dummy* pVal)
{
	(void)pVal;


	(*(pVal)) = FALSE;
}


flag CAN_Samv71_Rtems_Address_IsConstraintValid(const CAN_Samv71_Rtems_Address* pVal, int* pErrCode)
{
    flag ret = TRUE;
    switch (pVal->kind) {
        case static_can_id_PRESENT : 
            ret = CAN_Samv71_Rtems_Can_Id_IsConstraintValid((&(pVal->u.static_can_id)), pErrCode);
            break;          
        case application_control_can_id_PRESENT : 
            ret = CAN_Samv71_Rtems_Dummy_IsConstraintValid((&(pVal->u.application_control_can_id)), pErrCode);
            break;          
        default: /*COVERAGE_IGNORE*/
    	    *pErrCode = ERR_CAN_SAMV71_RTEMS_ADDRESS;      /*COVERAGE_IGNORE*/
    	    ret = FALSE;                               /*COVERAGE_IGNORE*/
    }

	return ret;
}

void CAN_Samv71_Rtems_Address_Initialize(CAN_Samv71_Rtems_Address* pVal)
{
	(void)pVal;


	pVal->kind = static_can_id_PRESENT;
	CAN_Samv71_Rtems_Can_Id_Initialize((&(pVal->u.static_can_id)));
}


flag CAN_Samv71_Rtems_Conf_T_IsConstraintValid(const CAN_Samv71_Rtems_Conf_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = CAN_Samv71_Rtems_Interface_T_IsConstraintValid((&(pVal->can_interface)), pErrCode);
    if (ret) {
        if (pVal->exist.bit_rate_prescaler) {
        	ret = CAN_Samv71_Rtems_Data_Bit_Rate_Prescaler_IsConstraintValid((&(pVal->bit_rate_prescaler)), pErrCode);
        }
        if (ret) {
            if (pVal->exist.synchronization_jump) {
            	ret = CAN_Samv71_Rtems_Data_Synchronization_Jump_Width_IsConstraintValid((&(pVal->synchronization_jump)), pErrCode);
            }
            if (ret) {
                if (pVal->exist.time_segments_after_sample_point) {
                	ret = CAN_Samv71_Rtems_Data_Time_Segment_After_Sample_Point_IsConstraintValid((&(pVal->time_segments_after_sample_point)), pErrCode);
                }
                if (ret) {
                    if (pVal->exist.time_segments_before_sample_point) {
                    	ret = CAN_Samv71_Rtems_Data_Time_Segment_Before_Sample_Point_IsConstraintValid((&(pVal->time_segments_before_sample_point)), pErrCode);
                    }
                    if (ret) {
                        if (pVal->exist.pck_source) {
                        	ret = CAN_Samv71_Rtems_PCK_Clock_Source_IsConstraintValid((&(pVal->pck_source)), pErrCode);
                        }
                        if (ret) {
                            if (pVal->exist.pck_prescaler) {
                            	ret = CAN_Samv71_Rtems_PCK_Prescaler_IsConstraintValid((&(pVal->pck_prescaler)), pErrCode);
                            }
                            if (ret) {
                                ret = CAN_Samv71_Rtems_Address_IsConstraintValid((&(pVal->address)), pErrCode);
                            }   /*COVERAGE_IGNORE*/
                        }   /*COVERAGE_IGNORE*/
                    }   /*COVERAGE_IGNORE*/
                }   /*COVERAGE_IGNORE*/
            }   /*COVERAGE_IGNORE*/
        }   /*COVERAGE_IGNORE*/
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void CAN_Samv71_Rtems_Conf_T_Initialize(CAN_Samv71_Rtems_Conf_T* pVal)
{
	(void)pVal;


	/*set can_interface */
	CAN_Samv71_Rtems_Interface_T_Initialize((&(pVal->can_interface)));
	/*set bit_rate_prescaler */
	pVal->exist.bit_rate_prescaler = 1;
	pVal->bit_rate_prescaler = 0UL;
	/*set synchronization_jump */
	pVal->exist.synchronization_jump = 1;
	pVal->synchronization_jump = 2UL;
	/*set time_segments_after_sample_point */
	pVal->exist.time_segments_after_sample_point = 1;
	pVal->time_segments_after_sample_point = 2UL;
	/*set time_segments_before_sample_point */
	pVal->exist.time_segments_before_sample_point = 1;
	pVal->time_segments_before_sample_point = 15UL;
	/*set pck_source */
	pVal->exist.pck_source = 1;
	pVal->pck_source = pck_clock_source_plla_clock;
	/*set pck_prescaler */
	pVal->exist.pck_prescaler = 1;
	pVal->pck_prescaler = 14UL;
	/*set address */
	CAN_Samv71_Rtems_Address_Initialize((&(pVal->address)));
}


