#ifndef GENERATED_ASN1SCC_samv71_rtems_serial_driver_H
#define GENERATED_ASN1SCC_samv71_rtems_serial_driver_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"

#ifdef  __cplusplus
extern "C" {
#endif


/*-- Serial_SamV71_Rtems_Device_T --------------------------------------------*/
/*-- Serial_SamV71_Rtems_Device_T_uart0 --------------------------------------------*/
typedef enum {
    pa10 = 0
} Serial_SamV71_Rtems_Device_T_uart0_tx;

// please use the following macros to avoid breaking code.
#define Serial_SamV71_Rtems_Device_T_uart0_tx_pa10 pa10
typedef enum {
    pa9 = 0
} Serial_SamV71_Rtems_Device_T_uart0_rx;

// please use the following macros to avoid breaking code.
#define Serial_SamV71_Rtems_Device_T_uart0_rx_pa9 pa9
typedef struct {
    Serial_SamV71_Rtems_Device_T_uart0_tx tx;
    Serial_SamV71_Rtems_Device_T_uart0_rx rx;

} Serial_SamV71_Rtems_Device_T_uart0;
/*-- Serial_SamV71_Rtems_Device_T_uart1 --------------------------------------------*/
typedef enum {
    pa4 = 0,
    pa6 = 1,
    uart1_tx_pd26 = 2
} Serial_SamV71_Rtems_Device_T_uart1_tx;

// please use the following macros to avoid breaking code.
#define Serial_SamV71_Rtems_Device_T_uart1_tx_pa4 pa4
#define Serial_SamV71_Rtems_Device_T_uart1_tx_pa6 pa6
#define Serial_SamV71_Rtems_Device_T_uart1_tx_pd26 uart1_tx_pd26
typedef enum {
    pa5 = 0
} Serial_SamV71_Rtems_Device_T_uart1_rx;

// please use the following macros to avoid breaking code.
#define Serial_SamV71_Rtems_Device_T_uart1_rx_pa5 pa5
typedef struct {
    Serial_SamV71_Rtems_Device_T_uart1_tx tx;
    Serial_SamV71_Rtems_Device_T_uart1_rx rx;

} Serial_SamV71_Rtems_Device_T_uart1;
/*-- Serial_SamV71_Rtems_Device_T_uart2 --------------------------------------------*/
typedef enum {
    uart2_tx_pd26 = 0
} Serial_SamV71_Rtems_Device_T_uart2_tx;

// please use the following macros to avoid breaking code.
#define Serial_SamV71_Rtems_Device_T_uart2_tx_pd26 uart2_tx_pd26
typedef enum {
    pd25 = 0
} Serial_SamV71_Rtems_Device_T_uart2_rx;

// please use the following macros to avoid breaking code.
#define Serial_SamV71_Rtems_Device_T_uart2_rx_pd25 pd25
typedef struct {
    Serial_SamV71_Rtems_Device_T_uart2_tx tx;
    Serial_SamV71_Rtems_Device_T_uart2_rx rx;

} Serial_SamV71_Rtems_Device_T_uart2;
/*-- Serial_SamV71_Rtems_Device_T_uart3 --------------------------------------------*/
typedef enum {
    pd30 = 0,
    pd31 = 1
} Serial_SamV71_Rtems_Device_T_uart3_tx;

// please use the following macros to avoid breaking code.
#define Serial_SamV71_Rtems_Device_T_uart3_tx_pd30 pd30
#define Serial_SamV71_Rtems_Device_T_uart3_tx_pd31 pd31
typedef enum {
    pd28 = 0
} Serial_SamV71_Rtems_Device_T_uart3_rx;

// please use the following macros to avoid breaking code.
#define Serial_SamV71_Rtems_Device_T_uart3_rx_pd28 pd28
typedef struct {
    Serial_SamV71_Rtems_Device_T_uart3_tx tx;
    Serial_SamV71_Rtems_Device_T_uart3_rx rx;

} Serial_SamV71_Rtems_Device_T_uart3;
/*-- Serial_SamV71_Rtems_Device_T_uart4 --------------------------------------------*/
typedef enum {
    pd3 = 0,
    pd19 = 1
} Serial_SamV71_Rtems_Device_T_uart4_tx;

// please use the following macros to avoid breaking code.
#define Serial_SamV71_Rtems_Device_T_uart4_tx_pd3 pd3
#define Serial_SamV71_Rtems_Device_T_uart4_tx_pd19 pd19
typedef enum {
    pd18 = 0
} Serial_SamV71_Rtems_Device_T_uart4_rx;

// please use the following macros to avoid breaking code.
#define Serial_SamV71_Rtems_Device_T_uart4_rx_pd18 pd18
typedef struct {
    Serial_SamV71_Rtems_Device_T_uart4_tx tx;
    Serial_SamV71_Rtems_Device_T_uart4_rx rx;

} Serial_SamV71_Rtems_Device_T_uart4;

typedef enum {
    Serial_SamV71_Rtems_Device_T_NONE,
    uart0_PRESENT,
    uart1_PRESENT,
    uart2_PRESENT,
    uart3_PRESENT,
    uart4_PRESENT
} Serial_SamV71_Rtems_Device_T_selection;

typedef union {
    Serial_SamV71_Rtems_Device_T_uart0 uart0;
    Serial_SamV71_Rtems_Device_T_uart1 uart1;
    Serial_SamV71_Rtems_Device_T_uart2 uart2;
    Serial_SamV71_Rtems_Device_T_uart3 uart3;
    Serial_SamV71_Rtems_Device_T_uart4 uart4;
} Serial_SamV71_Rtems_Device_T_unchecked_union;

typedef struct {
    Serial_SamV71_Rtems_Device_T_selection kind;

    Serial_SamV71_Rtems_Device_T_unchecked_union u;
} Serial_SamV71_Rtems_Device_T;

#define ERR_SERIAL_SAMV71_RTEMS_DEVICE_T_UART0_TX		201  /*pa10*/
flag Serial_SamV71_Rtems_Device_T_uart0_tx_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart0_tx* pVal, int* pErrCode);

#define ERR_SERIAL_SAMV71_RTEMS_DEVICE_T_UART0_RX		206  /*pa9*/
flag Serial_SamV71_Rtems_Device_T_uart0_rx_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart0_rx* pVal, int* pErrCode);

#define ERR_SERIAL_SAMV71_RTEMS_DEVICE_T_UART0		211  /**/
flag Serial_SamV71_Rtems_Device_T_uart0_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart0* pVal, int* pErrCode);

#define ERR_SERIAL_SAMV71_RTEMS_DEVICE_T_UART1_TX		216  /*pa4 | pa6 | pd26*/
flag Serial_SamV71_Rtems_Device_T_uart1_tx_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart1_tx* pVal, int* pErrCode);

#define ERR_SERIAL_SAMV71_RTEMS_DEVICE_T_UART1_RX		221  /*pa5*/
flag Serial_SamV71_Rtems_Device_T_uart1_rx_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart1_rx* pVal, int* pErrCode);

#define ERR_SERIAL_SAMV71_RTEMS_DEVICE_T_UART1		226  /**/
flag Serial_SamV71_Rtems_Device_T_uart1_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart1* pVal, int* pErrCode);

#define ERR_SERIAL_SAMV71_RTEMS_DEVICE_T_UART2_TX		231  /*pd26*/
flag Serial_SamV71_Rtems_Device_T_uart2_tx_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart2_tx* pVal, int* pErrCode);

#define ERR_SERIAL_SAMV71_RTEMS_DEVICE_T_UART2_RX		236  /*pd25*/
flag Serial_SamV71_Rtems_Device_T_uart2_rx_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart2_rx* pVal, int* pErrCode);

#define ERR_SERIAL_SAMV71_RTEMS_DEVICE_T_UART2		241  /**/
flag Serial_SamV71_Rtems_Device_T_uart2_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart2* pVal, int* pErrCode);

#define ERR_SERIAL_SAMV71_RTEMS_DEVICE_T_UART3_TX		246  /*pd30 | pd31*/
flag Serial_SamV71_Rtems_Device_T_uart3_tx_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart3_tx* pVal, int* pErrCode);

#define ERR_SERIAL_SAMV71_RTEMS_DEVICE_T_UART3_RX		251  /*pd28*/
flag Serial_SamV71_Rtems_Device_T_uart3_rx_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart3_rx* pVal, int* pErrCode);

#define ERR_SERIAL_SAMV71_RTEMS_DEVICE_T_UART3		256  /**/
flag Serial_SamV71_Rtems_Device_T_uart3_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart3* pVal, int* pErrCode);

#define ERR_SERIAL_SAMV71_RTEMS_DEVICE_T_UART4_TX		261  /*pd3 | pd19*/
flag Serial_SamV71_Rtems_Device_T_uart4_tx_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart4_tx* pVal, int* pErrCode);

#define ERR_SERIAL_SAMV71_RTEMS_DEVICE_T_UART4_RX		266  /*pd18*/
flag Serial_SamV71_Rtems_Device_T_uart4_rx_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart4_rx* pVal, int* pErrCode);

#define ERR_SERIAL_SAMV71_RTEMS_DEVICE_T_UART4		271  /**/
flag Serial_SamV71_Rtems_Device_T_uart4_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart4* pVal, int* pErrCode);

#define ERR_SERIAL_SAMV71_RTEMS_DEVICE_T		276  /**/
flag Serial_SamV71_Rtems_Device_T_IsConstraintValid(const Serial_SamV71_Rtems_Device_T* pVal, int* pErrCode);

void Serial_SamV71_Rtems_Device_T_uart0_tx_Initialize(Serial_SamV71_Rtems_Device_T_uart0_tx* pVal);
void Serial_SamV71_Rtems_Device_T_uart0_rx_Initialize(Serial_SamV71_Rtems_Device_T_uart0_rx* pVal);
void Serial_SamV71_Rtems_Device_T_uart0_Initialize(Serial_SamV71_Rtems_Device_T_uart0* pVal);
void Serial_SamV71_Rtems_Device_T_uart1_tx_Initialize(Serial_SamV71_Rtems_Device_T_uart1_tx* pVal);
void Serial_SamV71_Rtems_Device_T_uart1_rx_Initialize(Serial_SamV71_Rtems_Device_T_uart1_rx* pVal);
void Serial_SamV71_Rtems_Device_T_uart1_Initialize(Serial_SamV71_Rtems_Device_T_uart1* pVal);
void Serial_SamV71_Rtems_Device_T_uart2_tx_Initialize(Serial_SamV71_Rtems_Device_T_uart2_tx* pVal);
void Serial_SamV71_Rtems_Device_T_uart2_rx_Initialize(Serial_SamV71_Rtems_Device_T_uart2_rx* pVal);
void Serial_SamV71_Rtems_Device_T_uart2_Initialize(Serial_SamV71_Rtems_Device_T_uart2* pVal);
void Serial_SamV71_Rtems_Device_T_uart3_tx_Initialize(Serial_SamV71_Rtems_Device_T_uart3_tx* pVal);
void Serial_SamV71_Rtems_Device_T_uart3_rx_Initialize(Serial_SamV71_Rtems_Device_T_uart3_rx* pVal);
void Serial_SamV71_Rtems_Device_T_uart3_Initialize(Serial_SamV71_Rtems_Device_T_uart3* pVal);
void Serial_SamV71_Rtems_Device_T_uart4_tx_Initialize(Serial_SamV71_Rtems_Device_T_uart4_tx* pVal);
void Serial_SamV71_Rtems_Device_T_uart4_rx_Initialize(Serial_SamV71_Rtems_Device_T_uart4_rx* pVal);
void Serial_SamV71_Rtems_Device_T_uart4_Initialize(Serial_SamV71_Rtems_Device_T_uart4* pVal);
void Serial_SamV71_Rtems_Device_T_Initialize(Serial_SamV71_Rtems_Device_T* pVal);
typedef enum {
    b9600 = 0,
    b19200 = 1,
    b38400 = 2,
    b57600 = 3,
    b115200 = 4,
    b230400 = 5
} Serial_SamV71_Rtems_Baudrate_T;

// please use the following macros to avoid breaking code.
#define Serial_SamV71_Rtems_Baudrate_T_b9600 b9600
#define Serial_SamV71_Rtems_Baudrate_T_b19200 b19200
#define Serial_SamV71_Rtems_Baudrate_T_b38400 b38400
#define Serial_SamV71_Rtems_Baudrate_T_b57600 b57600
#define Serial_SamV71_Rtems_Baudrate_T_b115200 b115200
#define Serial_SamV71_Rtems_Baudrate_T_b230400 b230400

#define ERR_SERIAL_SAMV71_RTEMS_BAUDRATE_T		281  /*b9600 | b19200 | b38400 | b57600 | b115200 | b230400*/
flag Serial_SamV71_Rtems_Baudrate_T_IsConstraintValid(const Serial_SamV71_Rtems_Baudrate_T* pVal, int* pErrCode);

void Serial_SamV71_Rtems_Baudrate_T_Initialize(Serial_SamV71_Rtems_Baudrate_T* pVal);
typedef enum {
    even = 0,
    odd = 1,
    none = 2
} Serial_SamV71_Rtems_Parity_T;

// please use the following macros to avoid breaking code.
#define Serial_SamV71_Rtems_Parity_T_even even
#define Serial_SamV71_Rtems_Parity_T_odd odd
#define Serial_SamV71_Rtems_Parity_T_none none

#define ERR_SERIAL_SAMV71_RTEMS_PARITY_T		286  /*even | odd | none*/
flag Serial_SamV71_Rtems_Parity_T_IsConstraintValid(const Serial_SamV71_Rtems_Parity_T* pVal, int* pErrCode);

void Serial_SamV71_Rtems_Parity_T_Initialize(Serial_SamV71_Rtems_Parity_T* pVal);
typedef asn1SccUint Serial_SamV71_Escape_Byte_T;


#define ERR_SERIAL_SAMV71_ESCAPE_BYTE_T		291  /*(0..255)*/
flag Serial_SamV71_Escape_Byte_T_IsConstraintValid(const Serial_SamV71_Escape_Byte_T* pVal, int* pErrCode);

void Serial_SamV71_Escape_Byte_T_Initialize(Serial_SamV71_Escape_Byte_T* pVal);
typedef flag Serial_Samv71_Rtems_Dummy;


#define ERR_SERIAL_SAMV71_RTEMS_DUMMY		296  /**/
flag Serial_Samv71_Rtems_Dummy_IsConstraintValid(const Serial_Samv71_Rtems_Dummy* pVal, int* pErrCode);

void Serial_Samv71_Rtems_Dummy_Initialize(Serial_Samv71_Rtems_Dummy* pVal);
/*-- Serial_SamV71_Rtems_Mode_T --------------------------------------------*/
/*-- Serial_SamV71_Rtems_Mode_T_raw --------------------------------------------*/

typedef enum {
    Serial_SamV71_Rtems_Mode_T_raw_NONE,
    single_byte_PRESENT,
    custom_escape_byte_PRESENT
} Serial_SamV71_Rtems_Mode_T_raw_selection;

typedef union {
    Serial_Samv71_Rtems_Dummy single_byte;
    Serial_SamV71_Escape_Byte_T custom_escape_byte;
} Serial_SamV71_Rtems_Mode_T_raw_unchecked_union;

typedef struct {
    Serial_SamV71_Rtems_Mode_T_raw_selection kind;

    Serial_SamV71_Rtems_Mode_T_raw_unchecked_union u;
} Serial_SamV71_Rtems_Mode_T_raw;

typedef enum {
    Serial_SamV71_Rtems_Mode_T_NONE,
    escaped_packets_PRESENT,
    raw_PRESENT
} Serial_SamV71_Rtems_Mode_T_selection;

typedef union {
    flag escaped_packets;
    Serial_SamV71_Rtems_Mode_T_raw raw;
} Serial_SamV71_Rtems_Mode_T_unchecked_union;

typedef struct {
    Serial_SamV71_Rtems_Mode_T_selection kind;

    Serial_SamV71_Rtems_Mode_T_unchecked_union u;
} Serial_SamV71_Rtems_Mode_T;

#define ERR_SERIAL_SAMV71_RTEMS_MODE_T_RAW		326  /**/
#define ERR_SERIAL_SAMV71_RTEMS_MODE_T_RAW_SINGLE_BYTE_2		311  /**/
#define ERR_SERIAL_SAMV71_RTEMS_MODE_T_RAW_CUSTOM_ESCAPE_BYTE_2		321  /**/
flag Serial_SamV71_Rtems_Mode_T_raw_IsConstraintValid(const Serial_SamV71_Rtems_Mode_T_raw* pVal, int* pErrCode);

#define ERR_SERIAL_SAMV71_RTEMS_MODE_T		331  /**/
#define ERR_SERIAL_SAMV71_RTEMS_MODE_T_ESCAPED_PACKETS		301  /**/
flag Serial_SamV71_Rtems_Mode_T_IsConstraintValid(const Serial_SamV71_Rtems_Mode_T* pVal, int* pErrCode);

void Serial_SamV71_Rtems_Mode_T_raw_Initialize(Serial_SamV71_Rtems_Mode_T_raw* pVal);
void Serial_SamV71_Rtems_Mode_T_Initialize(Serial_SamV71_Rtems_Mode_T* pVal);
/*-- Serial_SamV71_Rtems_Conf_T --------------------------------------------*/
typedef struct {
    Serial_SamV71_Rtems_Device_T devname;
    Serial_SamV71_Rtems_Baudrate_T speed;
    Serial_SamV71_Rtems_Parity_T parity;
    Serial_SamV71_Rtems_Mode_T mode;

} Serial_SamV71_Rtems_Conf_T;

#define ERR_SERIAL_SAMV71_RTEMS_CONF_T		366  /**/
#define ERR_SERIAL_SAMV71_RTEMS_CONF_T_DEVNAME		336  /**/
#define ERR_SERIAL_SAMV71_RTEMS_CONF_T_SPEED_2		346  /**/
#define ERR_SERIAL_SAMV71_RTEMS_CONF_T_PARITY_2		356  /**/
#define ERR_SERIAL_SAMV71_RTEMS_CONF_T_MODE		361  /**/
flag Serial_SamV71_Rtems_Conf_T_IsConstraintValid(const Serial_SamV71_Rtems_Conf_T* pVal, int* pErrCode);

void Serial_SamV71_Rtems_Conf_T_Initialize(Serial_SamV71_Rtems_Conf_T* pVal);


/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */



#ifdef  __cplusplus
}

#endif

#endif
