/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>


#include "samv71-rtems-serial-driver.h"


flag Serial_SamV71_Rtems_Device_T_uart0_tx_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart0_tx* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) == pa10);
    *pErrCode = ret ? 0 :  ERR_SERIAL_SAMV71_RTEMS_DEVICE_T_UART0_TX;

	return ret;
}

flag Serial_SamV71_Rtems_Device_T_uart0_rx_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart0_rx* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) == pa9);
    *pErrCode = ret ? 0 :  ERR_SERIAL_SAMV71_RTEMS_DEVICE_T_UART0_RX;

	return ret;
}

flag Serial_SamV71_Rtems_Device_T_uart0_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart0* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = Serial_SamV71_Rtems_Device_T_uart0_tx_IsConstraintValid((&(pVal->tx)), pErrCode);
    if (ret) {
        ret = Serial_SamV71_Rtems_Device_T_uart0_rx_IsConstraintValid((&(pVal->rx)), pErrCode);
    }   /*COVERAGE_IGNORE*/

	return ret;
}

flag Serial_SamV71_Rtems_Device_T_uart1_tx_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart1_tx* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((((((*(pVal)) == pa4)) || (((*(pVal)) == pa6)))) || (((*(pVal)) == uart1_tx_pd26)));
    *pErrCode = ret ? 0 :  ERR_SERIAL_SAMV71_RTEMS_DEVICE_T_UART1_TX;

	return ret;
}

flag Serial_SamV71_Rtems_Device_T_uart1_rx_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart1_rx* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) == pa5);
    *pErrCode = ret ? 0 :  ERR_SERIAL_SAMV71_RTEMS_DEVICE_T_UART1_RX;

	return ret;
}

flag Serial_SamV71_Rtems_Device_T_uart1_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart1* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = Serial_SamV71_Rtems_Device_T_uart1_tx_IsConstraintValid((&(pVal->tx)), pErrCode);
    if (ret) {
        ret = Serial_SamV71_Rtems_Device_T_uart1_rx_IsConstraintValid((&(pVal->rx)), pErrCode);
    }   /*COVERAGE_IGNORE*/

	return ret;
}

flag Serial_SamV71_Rtems_Device_T_uart2_tx_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart2_tx* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) == uart2_tx_pd26);
    *pErrCode = ret ? 0 :  ERR_SERIAL_SAMV71_RTEMS_DEVICE_T_UART2_TX;

	return ret;
}

flag Serial_SamV71_Rtems_Device_T_uart2_rx_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart2_rx* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) == pd25);
    *pErrCode = ret ? 0 :  ERR_SERIAL_SAMV71_RTEMS_DEVICE_T_UART2_RX;

	return ret;
}

flag Serial_SamV71_Rtems_Device_T_uart2_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart2* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = Serial_SamV71_Rtems_Device_T_uart2_tx_IsConstraintValid((&(pVal->tx)), pErrCode);
    if (ret) {
        ret = Serial_SamV71_Rtems_Device_T_uart2_rx_IsConstraintValid((&(pVal->rx)), pErrCode);
    }   /*COVERAGE_IGNORE*/

	return ret;
}

flag Serial_SamV71_Rtems_Device_T_uart3_tx_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart3_tx* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((((*(pVal)) == pd30)) || (((*(pVal)) == pd31)));
    *pErrCode = ret ? 0 :  ERR_SERIAL_SAMV71_RTEMS_DEVICE_T_UART3_TX;

	return ret;
}

flag Serial_SamV71_Rtems_Device_T_uart3_rx_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart3_rx* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) == pd28);
    *pErrCode = ret ? 0 :  ERR_SERIAL_SAMV71_RTEMS_DEVICE_T_UART3_RX;

	return ret;
}

flag Serial_SamV71_Rtems_Device_T_uart3_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart3* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = Serial_SamV71_Rtems_Device_T_uart3_tx_IsConstraintValid((&(pVal->tx)), pErrCode);
    if (ret) {
        ret = Serial_SamV71_Rtems_Device_T_uart3_rx_IsConstraintValid((&(pVal->rx)), pErrCode);
    }   /*COVERAGE_IGNORE*/

	return ret;
}

flag Serial_SamV71_Rtems_Device_T_uart4_tx_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart4_tx* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((((*(pVal)) == pd3)) || (((*(pVal)) == pd19)));
    *pErrCode = ret ? 0 :  ERR_SERIAL_SAMV71_RTEMS_DEVICE_T_UART4_TX;

	return ret;
}

flag Serial_SamV71_Rtems_Device_T_uart4_rx_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart4_rx* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) == pd18);
    *pErrCode = ret ? 0 :  ERR_SERIAL_SAMV71_RTEMS_DEVICE_T_UART4_RX;

	return ret;
}

flag Serial_SamV71_Rtems_Device_T_uart4_IsConstraintValid(const Serial_SamV71_Rtems_Device_T_uart4* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = Serial_SamV71_Rtems_Device_T_uart4_tx_IsConstraintValid((&(pVal->tx)), pErrCode);
    if (ret) {
        ret = Serial_SamV71_Rtems_Device_T_uart4_rx_IsConstraintValid((&(pVal->rx)), pErrCode);
    }   /*COVERAGE_IGNORE*/

	return ret;
}

flag Serial_SamV71_Rtems_Device_T_IsConstraintValid(const Serial_SamV71_Rtems_Device_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
    switch (pVal->kind) {
        case uart0_PRESENT : 
            ret = Serial_SamV71_Rtems_Device_T_uart0_IsConstraintValid((&(pVal->u.uart0)), pErrCode);
            break;          
        case uart1_PRESENT : 
            ret = Serial_SamV71_Rtems_Device_T_uart1_IsConstraintValid((&(pVal->u.uart1)), pErrCode);
            break;          
        case uart2_PRESENT : 
            ret = Serial_SamV71_Rtems_Device_T_uart2_IsConstraintValid((&(pVal->u.uart2)), pErrCode);
            break;          
        case uart3_PRESENT : 
            ret = Serial_SamV71_Rtems_Device_T_uart3_IsConstraintValid((&(pVal->u.uart3)), pErrCode);
            break;          
        case uart4_PRESENT : 
            ret = Serial_SamV71_Rtems_Device_T_uart4_IsConstraintValid((&(pVal->u.uart4)), pErrCode);
            break;          
        default: /*COVERAGE_IGNORE*/
    	    *pErrCode = ERR_SERIAL_SAMV71_RTEMS_DEVICE_T;      /*COVERAGE_IGNORE*/
    	    ret = FALSE;                               /*COVERAGE_IGNORE*/
    }

	return ret;
}

void Serial_SamV71_Rtems_Device_T_uart0_tx_Initialize(Serial_SamV71_Rtems_Device_T_uart0_tx* pVal)
{
	(void)pVal;


	(*(pVal)) = pa10;
}
void Serial_SamV71_Rtems_Device_T_uart0_rx_Initialize(Serial_SamV71_Rtems_Device_T_uart0_rx* pVal)
{
	(void)pVal;


	(*(pVal)) = pa9;
}
void Serial_SamV71_Rtems_Device_T_uart0_Initialize(Serial_SamV71_Rtems_Device_T_uart0* pVal)
{
	(void)pVal;


	/*set tx */
	Serial_SamV71_Rtems_Device_T_uart0_tx_Initialize((&(pVal->tx)));
	/*set rx */
	Serial_SamV71_Rtems_Device_T_uart0_rx_Initialize((&(pVal->rx)));
}
void Serial_SamV71_Rtems_Device_T_uart1_tx_Initialize(Serial_SamV71_Rtems_Device_T_uart1_tx* pVal)
{
	(void)pVal;


	(*(pVal)) = pa4;
}
void Serial_SamV71_Rtems_Device_T_uart1_rx_Initialize(Serial_SamV71_Rtems_Device_T_uart1_rx* pVal)
{
	(void)pVal;


	(*(pVal)) = pa5;
}
void Serial_SamV71_Rtems_Device_T_uart1_Initialize(Serial_SamV71_Rtems_Device_T_uart1* pVal)
{
	(void)pVal;


	/*set tx */
	Serial_SamV71_Rtems_Device_T_uart1_tx_Initialize((&(pVal->tx)));
	/*set rx */
	Serial_SamV71_Rtems_Device_T_uart1_rx_Initialize((&(pVal->rx)));
}
void Serial_SamV71_Rtems_Device_T_uart2_tx_Initialize(Serial_SamV71_Rtems_Device_T_uart2_tx* pVal)
{
	(void)pVal;


	(*(pVal)) = uart2_tx_pd26;
}
void Serial_SamV71_Rtems_Device_T_uart2_rx_Initialize(Serial_SamV71_Rtems_Device_T_uart2_rx* pVal)
{
	(void)pVal;


	(*(pVal)) = pd25;
}
void Serial_SamV71_Rtems_Device_T_uart2_Initialize(Serial_SamV71_Rtems_Device_T_uart2* pVal)
{
	(void)pVal;


	/*set tx */
	Serial_SamV71_Rtems_Device_T_uart2_tx_Initialize((&(pVal->tx)));
	/*set rx */
	Serial_SamV71_Rtems_Device_T_uart2_rx_Initialize((&(pVal->rx)));
}
void Serial_SamV71_Rtems_Device_T_uart3_tx_Initialize(Serial_SamV71_Rtems_Device_T_uart3_tx* pVal)
{
	(void)pVal;


	(*(pVal)) = pd30;
}
void Serial_SamV71_Rtems_Device_T_uart3_rx_Initialize(Serial_SamV71_Rtems_Device_T_uart3_rx* pVal)
{
	(void)pVal;


	(*(pVal)) = pd28;
}
void Serial_SamV71_Rtems_Device_T_uart3_Initialize(Serial_SamV71_Rtems_Device_T_uart3* pVal)
{
	(void)pVal;


	/*set tx */
	Serial_SamV71_Rtems_Device_T_uart3_tx_Initialize((&(pVal->tx)));
	/*set rx */
	Serial_SamV71_Rtems_Device_T_uart3_rx_Initialize((&(pVal->rx)));
}
void Serial_SamV71_Rtems_Device_T_uart4_tx_Initialize(Serial_SamV71_Rtems_Device_T_uart4_tx* pVal)
{
	(void)pVal;


	(*(pVal)) = pd3;
}
void Serial_SamV71_Rtems_Device_T_uart4_rx_Initialize(Serial_SamV71_Rtems_Device_T_uart4_rx* pVal)
{
	(void)pVal;


	(*(pVal)) = pd18;
}
void Serial_SamV71_Rtems_Device_T_uart4_Initialize(Serial_SamV71_Rtems_Device_T_uart4* pVal)
{
	(void)pVal;


	/*set tx */
	Serial_SamV71_Rtems_Device_T_uart4_tx_Initialize((&(pVal->tx)));
	/*set rx */
	Serial_SamV71_Rtems_Device_T_uart4_rx_Initialize((&(pVal->rx)));
}
void Serial_SamV71_Rtems_Device_T_Initialize(Serial_SamV71_Rtems_Device_T* pVal)
{
	(void)pVal;


	pVal->kind = uart0_PRESENT;
	Serial_SamV71_Rtems_Device_T_uart0_Initialize((&(pVal->u.uart0)));
}


flag Serial_SamV71_Rtems_Baudrate_T_IsConstraintValid(const Serial_SamV71_Rtems_Baudrate_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((((((((((((*(pVal)) == b9600)) || (((*(pVal)) == b19200)))) || (((*(pVal)) == b38400)))) || (((*(pVal)) == b57600)))) || (((*(pVal)) == b115200)))) || (((*(pVal)) == b230400)));
    *pErrCode = ret ? 0 :  ERR_SERIAL_SAMV71_RTEMS_BAUDRATE_T;

	return ret;
}

void Serial_SamV71_Rtems_Baudrate_T_Initialize(Serial_SamV71_Rtems_Baudrate_T* pVal)
{
	(void)pVal;


	(*(pVal)) = b9600;
}


flag Serial_SamV71_Rtems_Parity_T_IsConstraintValid(const Serial_SamV71_Rtems_Parity_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((((((*(pVal)) == even)) || (((*(pVal)) == odd)))) || (((*(pVal)) == none)));
    *pErrCode = ret ? 0 :  ERR_SERIAL_SAMV71_RTEMS_PARITY_T;

	return ret;
}

void Serial_SamV71_Rtems_Parity_T_Initialize(Serial_SamV71_Rtems_Parity_T* pVal)
{
	(void)pVal;


	(*(pVal)) = even;
}


flag Serial_SamV71_Escape_Byte_T_IsConstraintValid(const Serial_SamV71_Escape_Byte_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 255UL);
    *pErrCode = ret ? 0 :  ERR_SERIAL_SAMV71_ESCAPE_BYTE_T;

	return ret;
}

void Serial_SamV71_Escape_Byte_T_Initialize(Serial_SamV71_Escape_Byte_T* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}


flag Serial_Samv71_Rtems_Dummy_IsConstraintValid(const Serial_Samv71_Rtems_Dummy* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
    ret = TRUE;
    *pErrCode = 0;

	return ret;
}

void Serial_Samv71_Rtems_Dummy_Initialize(Serial_Samv71_Rtems_Dummy* pVal)
{
	(void)pVal;


	(*(pVal)) = FALSE;
}


flag Serial_SamV71_Rtems_Mode_T_raw_IsConstraintValid(const Serial_SamV71_Rtems_Mode_T_raw* pVal, int* pErrCode)
{
    flag ret = TRUE;
    switch (pVal->kind) {
        case single_byte_PRESENT : 
            ret = Serial_Samv71_Rtems_Dummy_IsConstraintValid((&(pVal->u.single_byte)), pErrCode);
            break;          
        case custom_escape_byte_PRESENT : 
            ret = Serial_SamV71_Escape_Byte_T_IsConstraintValid((&(pVal->u.custom_escape_byte)), pErrCode);
            break;          
        default: /*COVERAGE_IGNORE*/
    	    *pErrCode = ERR_SERIAL_SAMV71_RTEMS_MODE_T_RAW;      /*COVERAGE_IGNORE*/
    	    ret = FALSE;                               /*COVERAGE_IGNORE*/
    }

	return ret;
}

flag Serial_SamV71_Rtems_Mode_T_IsConstraintValid(const Serial_SamV71_Rtems_Mode_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
    switch (pVal->kind) {
        case escaped_packets_PRESENT : /*COVERAGE_IGNORE*/
            ret = TRUE;
            *pErrCode = 0;
            break;          /*COVERAGE_IGNORE*/
        case raw_PRESENT : 
            ret = Serial_SamV71_Rtems_Mode_T_raw_IsConstraintValid((&(pVal->u.raw)), pErrCode);
            break;          
        default: /*COVERAGE_IGNORE*/
    	    *pErrCode = ERR_SERIAL_SAMV71_RTEMS_MODE_T;      /*COVERAGE_IGNORE*/
    	    ret = FALSE;                               /*COVERAGE_IGNORE*/
    }

	return ret;
}

void Serial_SamV71_Rtems_Mode_T_raw_Initialize(Serial_SamV71_Rtems_Mode_T_raw* pVal)
{
	(void)pVal;


	pVal->kind = single_byte_PRESENT;
	pVal->u.single_byte = FALSE;
}
void Serial_SamV71_Rtems_Mode_T_Initialize(Serial_SamV71_Rtems_Mode_T* pVal)
{
	(void)pVal;


	pVal->kind = escaped_packets_PRESENT;
	pVal->u.escaped_packets = FALSE;
}


flag Serial_SamV71_Rtems_Conf_T_IsConstraintValid(const Serial_SamV71_Rtems_Conf_T* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = Serial_SamV71_Rtems_Device_T_IsConstraintValid((&(pVal->devname)), pErrCode);
    if (ret) {
        ret = Serial_SamV71_Rtems_Baudrate_T_IsConstraintValid((&(pVal->speed)), pErrCode);
        if (ret) {
            ret = Serial_SamV71_Rtems_Parity_T_IsConstraintValid((&(pVal->parity)), pErrCode);
            if (ret) {
                ret = Serial_SamV71_Rtems_Mode_T_IsConstraintValid((&(pVal->mode)), pErrCode);
            }   /*COVERAGE_IGNORE*/
        }   /*COVERAGE_IGNORE*/
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void Serial_SamV71_Rtems_Conf_T_Initialize(Serial_SamV71_Rtems_Conf_T* pVal)
{
	(void)pVal;


	/*set devname */
	Serial_SamV71_Rtems_Device_T_Initialize((&(pVal->devname)));
	/*set speed */
	Serial_SamV71_Rtems_Baudrate_T_Initialize((&(pVal->speed)));
	/*set parity */
	Serial_SamV71_Rtems_Parity_T_Initialize((&(pVal->parity)));
	/*set mode */
	Serial_SamV71_Rtems_Mode_T_Initialize((&(pVal->mode)));
}


