/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>

#include "samv71-rtems-serial-driver.h"

flag Serial_SamV71_Rtems_Device_T_IsConstraintValid(
	const Serial_SamV71_Rtems_Device_T *pVal, int *pErrCode)
{
	flag ret = TRUE;
	ret = ((((((((((*(pVal)) == uart0)) || (((*(pVal)) == uart1)))) ||
		   (((*(pVal)) == uart2)))) ||
		 (((*(pVal)) == uart3)))) ||
	       (((*(pVal)) == uart4)));
	*pErrCode = ret ? 0 : ERR_SERIAL_SAMV71_RTEMS_DEVICE_T;

	return ret;
}

void Serial_SamV71_Rtems_Device_T_Initialize(Serial_SamV71_Rtems_Device_T *pVal)
{
	(void)pVal;

	(*(pVal)) = uart0;
}

flag Serial_SamV71_Rtems_Baudrate_T_IsConstraintValid(
	const Serial_SamV71_Rtems_Baudrate_T *pVal, int *pErrCode)
{
	flag ret = TRUE;
	ret = ((((((((((((*(pVal)) == Serial_SamV71_Rtems_Baudrate_T_b9600)) ||
		       (((*(pVal)) == Serial_SamV71_Rtems_Baudrate_T_b19200)))) ||
		     (((*(pVal)) == Serial_SamV71_Rtems_Baudrate_T_b38400)))) ||
		   (((*(pVal)) == Serial_SamV71_Rtems_Baudrate_T_b57600)))) ||
		 (((*(pVal)) == Serial_SamV71_Rtems_Baudrate_T_b115200)))) ||
	       (((*(pVal)) == Serial_SamV71_Rtems_Baudrate_T_b230400)));
	*pErrCode = ret ? 0 : ERR_SERIAL_SAMV71_RTEMS_BAUDRATE_T;

	return ret;
}

void Serial_SamV71_Rtems_Baudrate_T_Initialize(
	Serial_SamV71_Rtems_Baudrate_T *pVal)
{
	(void)pVal;

	(*(pVal)) = Serial_SamV71_Rtems_Baudrate_T_b9600;
}

flag Serial_SamV71_Rtems_Parity_T_IsConstraintValid(
	const Serial_SamV71_Rtems_Parity_T *pVal, int *pErrCode)
{
	flag ret = TRUE;
	ret = ((((*(pVal)) == Serial_SamV71_Rtems_Parity_T_even)) ||
	       (((*(pVal)) == Serial_SamV71_Rtems_Parity_T_odd)));
	*pErrCode = ret ? 0 : ERR_SERIAL_SAMV71_RTEMS_PARITY_T;

	return ret;
}

void Serial_SamV71_Rtems_Parity_T_Initialize(Serial_SamV71_Rtems_Parity_T *pVal)
{
	(void)pVal;

	(*(pVal)) = Serial_SamV71_Rtems_Parity_T_even;
}

flag Serial_SamV71_Rtems_Conf_T_bits_IsConstraintValid(
	const Serial_SamV71_Rtems_Conf_T_bits *pVal, int *pErrCode)
{
	flag ret = TRUE;
	ret = ((7UL <= (*(pVal))) && ((*(pVal)) <= 8UL));
	*pErrCode = ret ? 0 : ERR_SERIAL_SAMV71_RTEMS_CONF_T_BITS;

	return ret;
}

flag Serial_SamV71_Rtems_Conf_T_IsConstraintValid(
	const Serial_SamV71_Rtems_Conf_T *pVal, int *pErrCode)
{
	flag ret = TRUE;
	ret = Serial_SamV71_Rtems_Device_T_IsConstraintValid((&(pVal->devname)),
							     pErrCode);
	if (ret) {
		if (pVal->exist.speed) {
			ret = Serial_SamV71_Rtems_Baudrate_T_IsConstraintValid(
				(&(pVal->speed)), pErrCode);
		}
		if (ret) {
			if (pVal->exist.parity) {
				ret = Serial_SamV71_Rtems_Parity_T_IsConstraintValid(
					(&(pVal->parity)), pErrCode);
			}
			if (ret) {
				if (pVal->exist.bits) {
					ret = Serial_SamV71_Rtems_Conf_T_bits_IsConstraintValid(
						(&(pVal->bits)), pErrCode);
				}
			} /*COVERAGE_IGNORE*/
		} /*COVERAGE_IGNORE*/
	} /*COVERAGE_IGNORE*/

	return ret;
}

void Serial_SamV71_Rtems_Conf_T_bits_Initialize(
	Serial_SamV71_Rtems_Conf_T_bits *pVal)
{
	(void)pVal;

	(*(pVal)) = 7UL;
}
void Serial_SamV71_Rtems_Conf_T_Initialize(Serial_SamV71_Rtems_Conf_T *pVal)
{
	(void)pVal;

	/*set devname */
	Serial_SamV71_Rtems_Device_T_Initialize((&(pVal->devname)));
	/*set speed */
	pVal->exist.speed = 1;
	Serial_SamV71_Rtems_Baudrate_T_Initialize((&(pVal->speed)));
	/*set parity */
	pVal->exist.parity = 1;
	Serial_SamV71_Rtems_Parity_T_Initialize((&(pVal->parity)));
	/*set bits */
	pVal->exist.bits = 1;
	Serial_SamV71_Rtems_Conf_T_bits_Initialize((&(pVal->bits)));
	/*set use_paritybit */
	pVal->exist.use_paritybit = 1;
	pVal->use_paritybit = FALSE;
}
